version: "1.0"

services:
  handler:
    container_name: handler
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileHandler
    networks:
      - my-net
    env_file:
      - .env
    volumes:
      - ./logs/handler:/opt/logs
    depends_on:
      - rabbitmq
  receiver:
    container_name: receiver
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileReceiver
    networks:
      - my-net
    env_file:
      - .env
    volumes:
      - ./logs/receiver:/opt/logs
    ports:
      - '8081:80'
    depends_on:
      - rabbitmq
  writer:
    container_name: writer
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileWriter
    networks:
      - my-net
    env_file:
      - .env
    volumes:
      - ./logs/writer:/opt/logs
    ports:
      - '8082:80'
    depends_on:
      - rabbitmq
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - '8083:80'
    networks:
      - my-net
    volumes:
      - ./logs/client:/opt/logs
    depends_on:
      - receiver
      - handler
      - writer
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    networks:
      - my-net
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

networks:
  my-net:
    driver: bridge